services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: refrigeration_api
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app


  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: igorefrigeration
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
